### ISSUE TITLE
Export method not working correctly

### ISSUE THREAD

**Issue by SamD64** [Iquis/rev2-wakeup-tool#31]
[2021-03-28 15:25:32] NotImplementedException: The method or operation is not implemented.
   at GGXrdWakeupDPUtil.Library.SlotInput.get_CleanInputs()
   at GGXrdWakeupDPUtil.Library.ReversalTool.TranslateIntoFile(String filePath, String input)
[2021-03-28 15:25:32] Failed to export inputs from Blockstun Reversal to file C:\Users\samxb\Documents\My Games\XRD Mods\Wakeup\Saved Reversals\SJIAD.ggrs

This is the log, I tried to export my inputs and it spit out this error. Build 0.8.1

**Comment by Iquis** [comment]
Can you send me the file you tried to export?

**Comment by SamD64** [comment]
It didn’t export anything, program threw out errors and ignored request for file export. 

Sorry for ambiguous wording on the GitHub issue, I’ll check tomorrow and see if I can replicate the bug when I’m at my computer or if a more recent build fixed it. If not I’ll send u a log, where does the script save logs to?

**Comment by Iquis** [comment]
My bad! I meant "what was the inputs you tried to export?"
I would like to reproduce this bug.

The log is stored where you save the exe file. It should be called Log.txt
